### ISSUE TITLE
Stickied Thread Appears unreadable on Dark Theme

### ISSUE THREAD

**Issue by MercifulZebra** [TheEnigmaBlade/leagueoflegends-css#12]
![leaguetheme](https://cloud.githubusercontent.com/assets/7116664/10222485/560a9d54-6822-11e5-9365-bb3be4fbd015.png)

![image](https://cloud.githubusercontent.com/assets/7116664/10222587/dc8ef2d0-6822-11e5-8d70-e688e2c9a9f6.png)

Browser: Chrome
Issue: Old stickied thread does not change background color on Dark theme.

Expected Behavior: Light Theme -- White background, black text. Dark Theme -- Black background, white text.

Actual Behavior: Light Theme -- White Background, black text. Dark Theme -- White background, white text.

**Comment by TheEnigmaBlade** [comment]
This is caused by RES keyboard navigation. If you don't use it, you may want to disable the feature in RES's settings.
