### ISSUE TITLE
Theme causes my cooling fans to max out

### ISSUE THREAD

**Issue by Doye7** [TheEnigmaBlade/leagueoflegends-css#18]
Browser: Chrome

Short description:Looking at the subreddit with animations causes my cooling fans to kick into max speed and my processor has to clock its self up just to view the page. Screenshot shows just the subreddit on my open tab with only background processes running.

Looks nice though

Screenshot: Attached
![screenshot temps](https://cloud.githubusercontent.com/assets/14937366/10241645/f68182a2-68ea-11e5-98ea-6f66fc80c16b.jpg)

**Comment by Evergetic** [comment]
Yeah, I got this aswell. Really annoying because I like having the page open all day.

**Comment by TheEnigmaBlade** [comment]
You can disable the effect (if you don't use the dark theme) by visiting the `na` subdomain (https://na.reddit.com/r/leagueoflegends). It'll be removed once worlds ends.

**Comment by TheEnigmaBlade** [comment]
No longer applies after worlds ended.
