### ISSUE TITLE
Moderator List possibly to small

### ISSUE THREAD

**Issue by mxhdev** [TheEnigmaBlade/leagueoflegends-css#19]
For my setup, the name of the first moderator in the list appears to be cut off.

**How to recreate the problem**
1. Scroll down 
2. Look at moderator box

**My setup**
- Windows 7
- Most recent version of Google Chrome (45.0.2454.101 m)
- Resolution: 1366 x 768

**Screenshots**
![cutoff1](https://cloud.githubusercontent.com/assets/14106200/10243263/baba4904-68f7-11e5-8069-53a82cf241e2.png)
![cutoff2](https://cloud.githubusercontent.com/assets/14106200/10243266/c11e20e0-68f7-11e5-9663-d7ede9993142.png)

**Comment by levanhieu-git** [comment]
The problem is when the message the moderator button takes up more than one line, then it cuts off the list.
