### ISSUE TITLE
Switch to hardware-accelerated header fog effect

### ISSUE THREAD

**Issue by TheEnigmaBlade** [TheEnigmaBlade/leagueoflegends-css#23]
The original method I developed for the fog used a translate transform on the fog pseudo-elements rather than the current `background-position` animation. Although properly working in Firefox, the pseudo-elements weren't clipped in Blink-based browsers (Chrome).

Basic changes to set up the transforms method includes:
- `theme.less`: uncomment `transform: translate3d(0, 0, 0);` lines, increase width of body pseudo-elements
- `animations.less`: uncomment `transform` lines, comment `background-position` lines

**Comment by schristmann** [comment]
You can reduce cpu a bit by simply not scaling the fog images. Also you have the animation area as 400px high even though the header is only 200, as a result you're animating a lot of content that is hidden behind other element.

You might also see improvements from making the images smaller. Right now you have a 1200x205 and a 2880x150 image. I don't know how well these browser renderers deal with animating large images but you might see improvement from tiling smaller ones.

**Comment by schristmann** [comment]
Here you go, here's a sample of the animation using a seamless tiled fog image and keyframe transforms that are hardware accelerated. http://craftymind.com/factory/cssanimation/animationtest.html

The key element here is that the image is a 1024px tiled image, so you can background-repeat it over any size you want. As long as you animate it by 1024 pixels from keyframe 0% to 100% it will always loop seamlessly.

**Comment by TheEnigmaBlade** [comment]
The images are scaled down and scaled back up in CSS to get them small enough to be uploaded to reddit.

The major problem with your sample (and the original problem I was having) can be seen if you scroll to the right. You can see the rest of the pseudo-element as it moves left.

![](http://i.imgur.com/XCOLuiR.png)

**Comment by schristmann** [comment]
How are you managing to scroll right? The body is set to overflow-x: hidden. I don't get any horizontal scrollbars in the browsers I've tested on Mac.

**Comment by TheEnigmaBlade** [comment]
Middle mouse button/scroll wheel, which works on both Firefox and Chrome.

**Comment by schristmann** [comment]
Ah I see now. So yeah the correct solution then is to use a pseudo element that is relative positioned instead, so you can set a hidden overflow on the parent #header element. I've reuploaded the example with a simple change.

http://craftymind.com/factory/cssanimation/animationtest.html

**Comment by TheEnigmaBlade** [comment]
Dammit, so not being relative was the entire problem I had all along.

**Comment by schristmann** [comment]
Yeah and make sure you add the display:block as well otherwise the browser will render the pseudo element as 0x0.

**Comment by TheEnigmaBlade** [comment]
_Now_ I remember why I never thought to relative position the pseudo-element...

![](http://i.imgur.com/lwFup5V.jpg)

I have a couple more ideas now, though. Might be able to take advantage of a 0px height and visible overflow.

**Comment by TheEnigmaBlade** [comment]
No longer applies after worlds ended.
