### ISSUE TITLE
Might be an issue with chrome, but definitely a sharp performance drop compared to the previous theme.

### ISSUE THREAD

**Issue by BaconPancakes** [TheEnigmaBlade/leagueoflegends-css#24]
Scrolling is much laggier than before. General responsiveness is slow. I'm using 64-bit chrome on 4K resolution, so it's a bit resource intensive on the integrated GPU but I'm not gonna bust out the dedicated GPU just to get smooth /r/leagueoflegends. Animation-less version runs a bit better but it's not perfectly smooth. Firefox is fine though; might be that chrome's hardware acceleration is shit.

Screenshot shows that the content loading can't keep up with fast scrolling.
![slow performance](https://cloud.githubusercontent.com/assets/6261265/10270626/7b1363ba-6ac5-11e5-9fdf-1fd222141af2.png)

My CPU isn't a potato though: mobile 4th gen quadcore i7. I am currently browsing while plugged in, so there's no worry about battery-power throttling. What this says is that the theme is not particularly optimized for setups like mine.

The easiest compromise here is to allow for a theme with less performance load, or even a "classic" option.

**Comment by TheEnigmaBlade** [comment]
If the animation isn't at fault, there isn't much I can do. It's not much different from other major themes on reddit.

Conclusion: Chrome sucks.

**Comment by BaconPancakes** [comment]
Definitely not an issue with any other reddit theme I've encountered. Oh well. Subreddit style disabled, I guess. Chrome sucks.
