### ISSUE TITLE
Dark theme causes issues with certain flair.

### ISSUE THREAD

**Issue by csilva235** [TheEnigmaBlade/leagueoflegends-css#3]
I know there is a post about the text in chat boxes on the dark theme, but there is also an issue with some of the user flair because of the dark theme. 

Examples would be CLG and TSM flair since they are dark on light background for the flair.

**Comment by csilva235** [comment]
In looking around, it looks like this might be a bit harder of a bug to fix since it would require looking through all the flair and modifying the image in a way that it doesn't change the colors, but also doesn't use the background to make the image. 

The CLG flair being a notable example as the logo is on a transparent background and putting a white background on the flair image compromises the integrity of the logo and it would look pretty bad on the dark theme's background color since it would kind of stand out in a bad way.

Might not be worth it to fix.

**Comment by SW1FT** [comment]
Can't you just put a gray background rule in the `tagline` div under `.titlebox .tagline`?
