### ISSUE TITLE
Framerate is Horrible in IE11

### ISSUE THREAD

**Issue by thespiffyneostar** [TheEnigmaBlade/leagueoflegends-css#4]
The New theme looks great but the framerate for IE11 is terrible.  This will most likely impact people who browse at work, and aren't allowed to install a better browser.  This is similar to an issue seen with the CSS of the /r/minecraft subreddit.

repro steps:
1. Open Internet Explorer 11
2. navigate to reddit.com/r/leagueoflegends
3. scroll the page up and down

Results: Performance is terrible

Expected results: Performance is manageable.

Possible solution: Try disabling the smoke effect.

**Comment by TheEnigmaBlade** [comment]
The animated fog is most likely the culprit. Does the issue exist if you scroll down such that the header is no longer in view?

**Comment by 1lann** [comment]
Yes, the animated fog and mist is definitely (from my findings) the culprit.

Here's a profile of /r/leagueoflegends (without any modifications) while scrolling around a bit:
<img width="1440" alt="screen shot 2015-10-01 at 4 09 19 pm" src="https://cloud.githubusercontent.com/assets/804919/10216003/9884516c-6858-11e5-9de1-4fb3577b293f.png">

The red bars at the top represent a render frame which took longer than 16.66 ms, which is 1/60th of a second which allows a page to be rendered at 60 fps. As you can see, there are a lot of them, and they shouldn't occur that often.

The bottom half of the profiler shows the areas the renderer is drawing. You can see that there are multiple large boxes which represent a lot of areas being drawn and overdrawn.

Here's a profile of /r/leagueoflegends with the animation and mist image removed from the body element and .footer-parent while scrolling around a bit:
<img width="1440" alt="screen shot 2015-10-01 at 4 32 28 pm" src="https://cloud.githubusercontent.com/assets/804919/10216543/77158d6c-685c-11e5-949e-dbd17ff87b28.png">

You can see that there are a lot less red bars, and the bottom half of the profiler shows that only one area is being drawn each frame (A lot less compared to the page with animations).

~~Unfortunately the lag still does occur, even if the fog is out of the viewport.~~
EDIT: Nope I take that back, the lag decreases when the fog is out of the viewport. (Well, at least CPU usage does).

**Comment by TheEnigmaBlade** [comment]
No longer applies after worlds ended.
