### ISSUE TITLE
Show status of scripting websites

### ISSUE THREAD

**Issue by ehmehe** [TheEnigmaBlade/leagueoflegends-css#7]
Maybe you should show the status of scripting websites (updated/outdated)

**Comment by TheEnigmaBlade** [comment]
What do you mean by "scripting websites"?

**Comment by ehmehe** [comment]
for example LeagueSharp

**Comment by 1lann** [comment]
I'm not sure why you would want to show the status of illegal scripting websites when it's clearly condemned by the moderators and against the subreddit rules.
